#!bin/bash

# Pull settings from settings.demo
resourceGroup=$(grep -Po "(?<=^resourceGroup=).*" settings.demo)
regName=$(grep -Po "(?<=^regName=).*" settings.demo)
clusterName=$(grep -Po "(?<=^clusterName=).*" settings.demo)
keyVaultName=$(grep -Po "(?<=^keyVaultName=).*" settings.demo)
locationName=$(grep -Po "(?<=^locationName=).*" settings.demo)

echo Resource Group $resourceGroup
echo Container Registry $regName
echo Cluster Name $clusterName
echo Location $locationName 
echo Vault $keyVaultName

az group show -g $resourceGroup -o table

read -p "Are you sure? [y/n] " ans
echo

if [ $ans = "y" ] 
then
	appID=$(az keyvault secret show --name "spID" --vault-name $keyVaultName --query "value" -o tsv)

	echo Deleting Service Principle $appID
	az ad sp delete --id $appID

	echo Deleting Resource Group $resourceGroup 
	az group delete -n $resourceGroup --yes
fi

